coffeelint.json
grammars/asciidoc.cson

New support for languages in code blocks

feat: add support for several languages in code blocks

---

grammars/asciidoc.cson
spec/asciidoc-spec.coffee

support markdown Headings syntax

feat: support markdown Headings syntax

---

grammars/asciidoc.cson

- dockerfile
- properties (git-config, java-properties)
- makefile
- perl and perl6
- toml

feat: extends supported languages for code block

---

.coffeelintignore
.gitignore
grammars/asciidoc.cson
settings/asciidoc.cson
spec/fixtures/asciidoctor-lang.adoc

- review regex
- add `name` attribute
- asciidoctor syntax and mardown syntax
- add SASS support
- fix several language bug
- **add AsciiDoctor comment support**

refactor: languages support

---

CONTRIBUTING.adoc
README.md

First go at some contributing guidelines / manual. Still a work in progress though.

feat: contributing guidelines

---

CONTRIBUTING.adoc

Added information I discovered about the grammar, how it works and how it's processed.

add more information about how the grammar works and how it's processed

---

grammars/language-asciidoc.cson
grammars/repositories/languages.cson
spec/code-block-generator-spec.coffee
spec/fixtures/asciidoctor-lang.adoc

- Mustache
- OCaml
- Scala
- Groovy
- JSX

Add new languages support for code block

---

CONTRIBUTING.adoc

Because great comments deserve to be documented.

doc: upstream regex info and warn

---

README.md
lib/main.coffee

Add badges because it's fun! :smile: 
[![Atom Package](https://img.shields.io/apm/v/language-asciidoc.svg)](https://atom.io/packages/language-asciido)
[![Atom Package Downloads](https://img.shields.io/apm/dm/language-asciidoc.svg)](https://atom.io/packages/language-asciido)
[![Build Status](https://travis-ci.org/asciidoctor/atom-language-asciidoc.svg?branch=master)](https://travis-ci.org/asciidoctor/atom-language-asciidoc)
[![MIT License](http://img.shields.io/badge/license-MIT-blue.svg?style=flat)](https://github.com/asciidoctor/atom-language-asciidoc/blob/master/LICENSE.md)

Add badges

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/link-macro-grammar.cson
spec/inlines/link-grammar-spec.coffee

Support for email highlight.
```adoc
foo@bar.com
```
Regex from AsciiDoctor code.

Email highlight

---

appveyor.yml

Add configuration file for [AppVeyor](https://ci.appveyor.com)
It's a free CI tool dedicate to Windows environment.
@mojavelinux can you activated the build on [AppVeyor](https://ci.appveyor.com) ?
Take the badge code on [badges page](https://ci.appveyor.com/project/asciidoctoratom-language-asciidocr/settings/badges), I would add the badge to this PR.

AppVeyor configuration

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/blocks/front-matter-grammar.cson
spec/blocks/front-matter-grammar-spec.coffee

Related to #56.
```adoc
---
receipt:     Oz-Ware Purchase Invoice
customer:
given:   Dorothy
items:
- part_no:   A4786
descrip:   Water Bucket (Filled)
price:     1.47
bill-to:  &id001
street: |
123 Tornado Alley
Suite 16
city:   East Centerville
specialDelivery:  >
Follow the Yellow Brick
Road to the Emerald City.
Pay no attention to the
man behind the curtain.
test: test
---
```

feat: front matter block support

---

grammars/repositories/inlines/emphasis-grammar.cson

I left some messy WIP comment in the original PR. this will clean it up.

refactor: remove messy comment

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/anchor-macro-grammar.cson
grammars/repositories/inlines/bibliography-anchor-grammar.cson
grammars/repositories/inlines/footnote-macro-grammar.cson
grammars/repositories/inlines/general-block-macro-grammar.cson
grammars/repositories/inlines/image-macro-grammar.cson
grammars/repositories/inlines/kbd-macro-grammar.cson
grammars/repositories/inlines/link-macro-grammar.cson
grammars/repositories/inlines/menu-macro-grammar.cson
grammars/repositories/inlines/passthrough-macro-grammar.cson
grammars/repositories/inlines/stem-grammar.cson
grammars/repositories/inlines/xref-macro-grammar.cson
spec/inlines/anchor-macro-grammar-spec.coffee
spec/inlines/attribute-reference-grammar-spec.coffee
spec/inlines/bibliography-anchor-grammar-spec.coffee
spec/inlines/characters-grammar-spec.coffee
spec/inlines/footnote-macro-grammar-spec.coffee
spec/inlines/general-block-macro-grammar-spec.coffee
spec/inlines/image-macro-grammar-spec.coffee
spec/inlines/kbd-macro-grammar-spec.coffee
spec/inlines/link-grammar-spec.coffee
spec/inlines/menu-macro-grammar-spec.coffee
spec/inlines/passthrough-macro-grammar-spec.coffee
spec/inlines/stem-grammar-spec.coffee
spec/inlines/xref-macro-grammar-spec.coffee
styles/asciidoc.atom-text-editor.less

Basic multi-lines for unambiguous elements.

feat: multi-lines

---

CONTRIBUTING.adoc
README.md

Add compatibility mode informations to the main readme.

doc: compatibility mode informations

---

CONTRIBUTING.adoc

To add labels and provide a guidance for getting started (sorry, somewhat of a combined PR).
Labels based on #105 
I was trying to go for some highlighting in accordance with the GitHub label colors. Unfortunately I couldn't easy find out how to do that, based on the Asciidoctor manual. Can I get some writing/coding advice?

doc: project organization and getting started

---

CONTRIBUTING.adoc
package.json

- chore: better Atom version definition.
- doc: update spec section

Documentation & Atom

---

package.json

chore: add keywords/tags

---

grammars/language-asciidoc.cson
grammars/repositories/blocks/example-grammar.cson
grammars/repositories/blocks/literal-grammar.cson
grammars/repositories/blocks/open-grammar.cson
grammars/repositories/blocks/sidebar-grammar.cson

feat: fix wrong end block

---

lib/main.coffee

Compatibility for Atom < 1.11
Related to #164

feat: support grammar reload for Atom < 1.11

---

.travis.yml
appveyor.yml
package.json

Related to https://github.com/atom/ci

chore: update CI configuration.

---

grammars/language-asciidoc.cson

related to https://github.com/atom/atom/pull/13820

chore: Opt out of new line length limit behavior.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.adoc

Fix sentences in contributing doc and pull request template.

fix sentences in contributing doc and pull request template
