styles/asciidoc.atom-text-editor.less

- use `&` instead of repeat `.markup`
- fix font smoothing
- remove custom bullet style to use default style for better readability

LESS optimize syntax

---

grammars/asciidoc.cson
spec/asciidoc-spec.coffee

Using a lazy quantifier and a lookahead to ensure
that the highlight will break at the first
underscore followed by a space or line end.
Fixes issue #21.

fix: italic highlight with underscores

---

.travis.yml
package.json
spec/asciidoc-spec.coffee

- useful for Travis CI
Related to #32
Build script (https://raw.githubusercontent.com/atom/ci/master/build-package.sh) have a special section for run automatically CoffeeLint if is present.
```bash
if [ -f ./node_modules/.bin/coffeelint ]; then
if [ -d ./lib ]; then
echo "Linting package..."
./node_modules/.bin/coffeelint lib
rc=$?; if [ $rc -ne 0 ]; then exit $rc; fi
fi
if [ -d ./spec ]; then
echo "Linting package specs..."
./node_modules/.bin/coffeelint spec
rc=$?; if [ $rc -ne 0 ]; then exit $rc; fi
fi
fi
```

feat: add CoffeeLint as dev dependencies

---

spec/asciidoc-spec.coffee

This issue will fix special characters breaking block title highlighting.

fix: special chars in block titles

---

grammars/asciidoc.cson

Porting the https://github.com/asciidoctor/asciidoctor/blob/v1.5.4/lib/asciidoctor.rb#L1177-L1178 to the grammar.
fix #38

Porting AsciiDoctor regex for monospace

---

grammars/asciidoc.cson
grammars/properties-lang.cson
spec/asciidoc-spec.coffee
spec/fixtures/asciidoctor-lang.adoc
spec/properties-lang-spec.coffee

**Note:**
I use `grammar.tokenizeLines` in the tests because `grammar.tokenizeLine` doesn't work properly with multi-lines content.
- `grammar.tokenizeLine` give false positive with multi-lines because it parse multi-lines as a single line.
Fix #20, #39,  #59

refactor: code block scope

---

CONTRIBUTING.adoc

Wrong list level  in `Generate the grammar file` section.

doc: fix list level

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/inlines/inlines-grammar.cson
grammars/repositories/partials/list-grammar.cson
spec/asciidoc-bold-spec.coffee
spec/asciidoc-spec.coffee
styles/asciidoc.atom-text-editor.less

Adds bold highlighting, not conflicting with bullet lists, and
supporting multi-line highlighting.
Adds todo list highlighting, in a simple form.
The features are developed synchronously to avoid collisions on the
[*] asterisk based todo items.
The commit originates from pull request no 45 which was re-implemented
on top of the new grammar structure.

feat: bold highlighting and todo

---

grammars/language-asciidoc.cson
grammars/repositories/blocks/quote-grammar.cson
spec/blocks/quote-grammar-spec.coffee

The last part's of the #27:
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility
```asciidoc
foobar
foobar
> I don't like it, and I'm sorry I ever had anything to do with it.
> Erwin Schrödinger, Sorry
foobar foobar
foobar
foobar
> I've got Markdown in my AsciiDoc!
>
> *strong*
> Yep. AsciiDoc and Markdown share a lot of common syntax already.
foobar
```

Markdown-style block quotes support

---

grammars/language-asciidoc.cson
grammars/repositories/blocks/admonition-grammar.cson
spec/blocks/admonition-grammar-spec.coffee

Admonition multi-lines support.
```asciidoc
foobar
NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is *determined* by the label
at the _beginning_ of the paragraph.
Here are the other built-in admonition types:
TIP: a *pro* _tip_...
IMPORTANT: Don't *forget* icon:megaphone[]
WARNING: Watch out for...
CAUTION: Ensure that...
```

Admonition multi-lines support

---

.travis.yml
CONTRIBUTING.adoc
lib/grammar-helper.coffee
lib/main.coffee
spec/code-block-generator-spec.coffee
spec/grammar-helper-spec.coffee

In Dev Mode, edit grammars `.cson` files and immediately see the changes in `.adoc` files.  :dizzy:  :sparkles:
- No longer white flash when compile grammar.

🚀 Grammar live reload 🚀

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/monospaced-grammar.cson
spec/inlines/monospaced-grammar-spec.coffee

- don't capture preceding character
- don't match escaped monospaced pattern
- simply match for attribute list
- use non-capturing groups

correct monospaced phrase matches

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/partials/line-break-grammar.cson
spec/partials/line-break-grammar-spec.coffee

Add line break support.
```asciidoc
+
Foo +
Rubies are *red* +
_Topazes_ are blue.
[%hardbreaks]
Ruby is red.
Java is black.
```
Fix #42

Add line break support

---

grammars/language-asciidoc.cson
grammars/repositories/partials/titles-grammar.cson
spec/partials/titles-grammar-spec.coffee
styles/asciidoc.atom-text-editor.less

This feature distinguishes headers into their separate levels (0-5). this enables custom styling in the future. This feature mirrors the naming used in the GitHub flavored Markdown (GFM) language package.
On this visual side this feature changes nothing, it's just creating potential.

feat: header level distinction

---

CONTRIBUTING.adoc

As discussed in pull request no 4, introducing compatibility mode is not recommended. This technical decision is now documented in the Contributing guidelines.

doc: no compat mode supported

---

grammars/language-asciidoc.cson
grammars/repositories/partials/titles-grammar.cson
spec/partials/titles-grammar-spec.coffee
styles/asciidoc.atom-text-editor.less

The recent changes breaks the heading style with some theme.
Currently (dev mode):
With my changes:
I have try with several themes.

Heading style

---

grammars/language-asciidoc.cson
grammars/repositories/partials/line-break-grammar.cson
spec/partials/line-break-grammar-spec.coffee

Require that the line have at least one non-blank character before the line break syntax.

make hard line break match more strict

---

README.md

To summarize the discussion in PR #70, where the explicit info on the .txt support is desired, but the recommended customization is through the Atom config, rather than through the Grammar modification.
Credits go to @bwklein and @ldez

doc: file ext support

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/strong-grammar.cson
spec/inlines/strong-grammar-spec.coffee

- don't match strong phrase that is escaped (single for constrained, double for unconstrained)
- simplify match for attribute list
- don't capture unnecessary groups

don't match strong phrase that is escaped

---

grammars/language-asciidoc.cson
lib/code-block-generator.coffee
spec/blocks/code-block-grammar-spec.coffee
spec/code-block-generator-spec.coffee
spec/partials/block-callout-grammar-spec.coffee

```adoc
[source,ruby,subs=attributes+]
----
source 'https://rubygems.org'
gem 'asciidoctor', '{latest-release}'
----
```
Fix #93

Allow additional attributes to be defined on source block

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/footnote-macro-grammar.cson
spec/inlines/footnote-macro-grammar-spec.coffee
styles/asciidoc.atom-text-editor.less

- match inline patterns inside footnote content
- change name of match to markup.other.footnote.asciidoc
- skip escaped footnote
- add CSS for footnote (map to function color)

resolves #43 support text formatting in footnote content

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/monospaced-grammar.cson

This is primarily an internal change that makes the grammar more accurate.

order unconstrained monospace before constrained

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/blocks/open-grammar.cson
snippets/language-asciidoc.cson
spec/blocks/open-grammar-spec.coffee

Complete rewrite of snippets.
- add more snippets
- add `descriptionMoreURL` to link with the [AsciiDoctor documentation](http://asciidoctor.org/docs/user-manual)
Notes:
- I have prefix literal words by a `a` (like **a**sciidoc) to limit unwanted suggestions
- snippets with prefix starts with a  punctuation characters: no popup but works
- To see all the available snippets for the file type that you currently have open, you can type <kbd>alt-shift-S</kbd>.
- press <kbd>Tab</kbd> to apply snippets.
Fix #23

Complete rewrite of snippets.

---

styles/asciidoc.atom-text-editor.less

> the shadow DOM is now enabled by default to prevent style pollution in Atom’s text editor component.
http://blog.atom.io/2015/01/05/enable-shadow-dom.html

feat: use Shadow DOM

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/anchor-macro-grammar.cson
grammars/repositories/inlines/attribute-reference-grammar.cson
grammars/repositories/inlines/characters-grammar.cson
grammars/repositories/inlines/image-macro-grammar.cson
grammars/repositories/inlines/kbd-macro-grammar.cson
grammars/repositories/inlines/link-macro-grammar.cson
grammars/repositories/inlines/menu-macro-grammar.cson
grammars/repositories/inlines/stem-grammar.cson

Preventing substitutions:
- characters
- attribute reference
- anchor macro
- image macro
- kbd macro
- link macro
- menu macro
- stem macro
```adoc
\&sect; will appear as an entity, not the &sect; symbol. FAILED
\{two-semicolons} will appear {two-semicolons}, not resolved as ;;. FAILED
\[[idname]] foo  [[idname]]
\anchor:idname[] foo anchor:idname[]
\stem:[x != 0] foo stem:[x != 0]
\asciimath:[x != 0] foo asciimath:[x != 0]
\latexmath:[\sqrt(1) = 2] foo latexmath:[\sqrt(1) = 2]
\kbd:[Save] foo kbd:[Save]
\menu:File[New...] foo menu:File[New...]
\link:path[label] foo link:path[label]
```

feat: Preventing substitutions

---

snippets/language-asciidoc.cson

Two snippets for the easy creation of both unchecked and checked checklist items.
Originally I was aiming for the `-[` snippet, but that raises issues if the editor automatically closes the first `[` bracket with a second `]` bracket after the cursor. Using the lower-case characters `o` and `x` resolve this, whilst symbolizing the check rendering.

feat: checklist snippets

---

snippets/language-asciidoc.cson

Man pages require a special document structure. This snippet gets you started.

add template for man page to snippets

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/attribute-reference-grammar.cson
grammars/repositories/inlines/link-macro-grammar.cson
grammars/repositories/partials/attributes-grammar.cson
grammars/repositories/partials/hard-break-backslash-grammar.cson
grammars/repositories/partials/line-break-backslash-grammar.cson
spec/inlines/attribute-reference-grammar-spec.coffee
spec/inlines/link-grammar-spec.coffee
spec/partials/attributes-grammar-spec.coffee

Use attributes references with url
```adoc
{uri-repo}[Asciidoctor]
[{uri-repo}[Asciidoctor]
({uri-repo}[Asciidoctor]
<{uri-repo}[Asciidoctor]
>{uri-repo}[Asciidoctor]
foo {uri-repo}[Asciidoctor] bar
link:http://{uri-repo}[label]
[link:{uri-repo}[label]
(link:{uri-repo}[label]
<link:{uri-repo}[label]
>link:{uri-repo}[label]
foo link:{uri-repo}[label] bar
Go on link:https://foobar.com now
http://foo{uri-repo}bar.com
<http://foobar.com[foobar]
>http://foobar.com[foobar]
(http://foobar.com[foobar]
[http://foobar.com[foobar]
foo http://foobar.com[foobar] bar
```

feat: url with attributes references

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/inlines/mark-grammar.cson
spec/inlines/mark-grammar-spec.coffee
styles/asciidoc.atom-text-editor.less

http://asciidoctor.org/docs/user-manual/#custom-styling-with-attributes
```adoc
.foobar
[role]**foo** bar
[role]*foo* bar
[role]__foo__ bar
[role]_foo_ bar
[role]##foo## bar
[role role2]#foo# bar
[role]``foo`` bar
[role]`foo` bar
[role]^foo^bar^foo^bar
[role]~foo~bar~foo~bar
```

feat: add mark support

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/inlines/typographic-quotes-grammar.cson
spec/inlines/typographic-quotes-grammar-spec.coffee
styles/asciidoc.atom-text-editor.less

Quotation Marks and Apostrophes: http://asciidoctor.org/docs/user-manual/#curved
```adoc
foo [bar]"`double-quoted`" foo
foo [bar]'`single-quoted`' foo
foo "`double-quoted`" foo
foo '`single-quoted`' foo
```

feat: typographic quotes

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/attribute-reference-grammar.cson
spec/inlines/attribute-reference-grammar-spec.coffee

Highlighting inline attribute definition like others attribute definitions.
```adoc
{set:attrname!:value}
{counter:pcount:1}
{counter2:pcount:1}
{set:foo:bar}
{set:name!}
```

feat: inline assignement

---

grammars/language-asciidoc.cson
grammars/repositories/blocks/admonition-paragraph-grammar.cson
grammars/repositories/blocks/passthrough-paragraph-grammar.cson
grammars/repositories/blocks/quote-paragraph-grammar.cson
grammars/repositories/partials/block-attribute-inner-grammar.cson
spec/blocks/quote-paragraph-grammar-spec.coffee

Support `%` and `.` for:
- quotes
- admonition
- pass-through
```adoc
[quote#someone-quote]
This is just a quote from someone.
[quote.famous]
This is just a quote from someone.
[quote#someone-quote.famous]
This is just a quote from someone.
[quote#id]
This is just a quote from someone.
[quote.role]
This is just a quote from someone.
[quote%option]
This is just a quote from someone.
[quote.role#id]
This is just a quote from someone.
[quote#id.role]
This is just a quote from someone.
[quote%option#id]
This is just a quote from someone.
[quote.role%option]
This is just a quote from someone.
```

refactor: enhance block attribute matching

---

CONTRIBUTING.adoc
appveyor.yml

Skip AppVeyor builds when asciidoctor-docbot commit.

chore: skip AppVeyor on publishing commits

---

grammars/language-asciidoc.cson
grammars/repositories/partials/list-grammar.cson
spec/partials/list-labeled-grammar-spec.coffee

url and attribute reference within list definition.
```adoc
{uri-asciidoctorjs-npm}[asciidoctor.js]:: the main npm package for Asciidoctor.js
{uri-grunt-asciidoctor-npm}[grunt-asciidoctor]:: an npm package for processing AsciiDoc source files in your {uri-gruntjs}[Grunt] project
{foo_term}:: {foo_def}
```
Your screenshot.

feat: url and attribute reference within list definition

---

grammars/language-asciidoc.cson
grammars/repositories/inlines/general-block-macro-grammar.cson
grammars/repositories/partials/block-callout-grammar.cson
grammars/repositories/partials/include-directive-grammar.cson
lib/code-block-generator.coffee
spec/blocks/source-literal-grammar-spec.coffee
spec/code-block-generator-spec.coffee
spec/inlines/general-block-macro-grammar-spec.coffee
spec/partials/block-callout-grammar-spec.coffee

Source block delimiter with literal delimiter.
~~Bonus: inception mode (highlight asciidoc source in asciidoc source block...)~~
```adoc
= Source block delimiter ....
== Exemple
[source,adoc]
....
:testdir: ${project.build.testSourceDirectory} // <1>
:testpkg: {testdir}/org/asciidoctor // <2>
[source,java]
----
include::{testpkg}/WhenAttributesAreUsed.java[tag=uri-scheme] // <3>
----
<1> Positionne l'attribut permettant de masquer le schéma sur les liens
....
// <1> Utilise une variable du build Maven (filtering)
// <2> Réutilise la variable définie juste au dessus pour ajouter le package
// <3> Précise le tag à utiliser (possibilité de préciser plusieurs tag séparé par des virgules)
== Résultat
:testpkg: src/test/java/org/asciidoctor
[source,java,indent=0]
---- …
```

feat: source and literal delimiter

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/blocks/comment-open-block-grammar.cson
spec/blocks/comment-open-block-grammar-spec.coffee
spec/partials/block-attribute-explicit-paragraph-grammar-spec.coffee

Highlighting for comment 'open block'.
```adoc
foo
[comment]
--
an open block comment.
an open block comment.
an open block comment.
--
foo
```

feat: comment open block

---

grammars/language-asciidoc.cson
grammars/repositories/blocks/open-grammar.cson
spec/blocks/open-block-grammar-spec.coffee
styles/asciidoc.atom-text-editor.less

Open block as Asciidoc code block.
```adoc
Using Bundler::
+
--
Add the `jekyll-asciidoc` plugin gem to your [path]_Gemfile_:
[source,ruby]
----
group :jekyll_plugins do
gem 'jekyll-asciidoc'
end
----
Then, run the Bundler command to install it:
$ bundle install
--
```
Fix #154

Open block as asciidoc code block

---

package.json
styles/asciidoc.atom-text-editor.less

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary.
This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`.
Fix #170

chore: shadow DOM compatibility migration

---

grammars/language-asciidoc.cson
grammars/repositories/asciidoc-grammar.cson
grammars/repositories/blocks/listing-paragraph-grammar.cson
spec/blocks/listing-block-grammar-spec.coffee

- support listing block
```adoc
== Heading
== Heading
This para is highlighted normally.
[listing]
----
This is a listing.
----
Everything after here is good.
```
Fix #161

feat: support listing block.

---

lib/main.coffee

Due to changes in Atom, grammar hot-reload in Dev Mode is broken.

fix: dev grammar hotreload.

---

grammars/language-asciidoc.cson
grammars/repositories/blocks/admonition-paragraph-grammar.cson
grammars/repositories/blocks/comment-paragraph-grammar.cson
grammars/repositories/blocks/example-grammar.cson
grammars/repositories/blocks/listing-paragraph-grammar.cson
grammars/repositories/blocks/literal-paragraph-grammar.cson
grammars/repositories/blocks/passthrough-paragraph-grammar.cson
grammars/repositories/blocks/quote-paragraph-grammar.cson
grammars/repositories/blocks/sidebar-paragraph-grammar.cson
lib/code-block-generator.coffee
spec/blocks/admonition-block-grammar-spec.coffee
spec/blocks/comment-open-block-grammar-spec.coffee
spec/blocks/example-open-block-grammar-spec.coffee
spec/blocks/example-paragraph-grammar-spec.coffee
spec/blocks/listing-block-grammar-spec.coffee
spec/blocks/listing-open-block-grammar-spec.coffee
spec/blocks/literal-open-block-grammar-spec.coffee
spec/blocks/literal-paragraph-grammar-spec.coffee
spec/blocks/passthrough-block-grammar-spec.coffee
spec/blocks/passthrough-open-block-grammar-spec.coffee
spec/blocks/quote-air-block-grammar-spec.coffee
spec/blocks/quote-block-grammar-spec.coffee
spec/blocks/quote-open-block-grammar-spec.coffee
spec/blocks/sidebar-open-block-grammar-spec.coffee
spec/blocks/sidebar-paragraph-grammar-spec.coffee
spec/blocks/source-block-grammar-spec.coffee
spec/blocks/source-literal-grammar-spec.coffee
spec/blocks/source-open-block-grammar-spec.coffee
spec/code-block-generator-spec.coffee
spec/partials/block-callout-grammar-spec.coffee

This PR removes the `[\\r\\n]+` requirement present in some end patterns.  This regex wasn't really doing anything important in the first place (all it was contributing was a zero-width match at the end of the line).  In addition, due to atom/first-mate#100, newlines are no longer added to the last line of the file, meaning that rules containing `[\\r\\n]+` would fail to match on the last line.  Therefore, this change is simply a backwards-compatible change to ensure that language-asciidoc continues working as before on Atom 1.22+.
I hope I did the whole grammar generation correctly!
/cc @Ingramz
Refs atom/atom#15729

Do not attempt to match newline characters
